# OBSOLETE: alte u-Formel (u_odd != 1), siehe _scripts/d_eff_ledger_corrected.py (Loop 39).
"""Extended Capacity-Census nach GPT-Feedback (2026-05-05)
Drei neue Spalten:
  A) Level-Lowering Capacity: C_LL(ell) = log(prod{p|N : ell|v_p(Delta)})
  B) S-Unit Congruence Capacity: Ordnung der von S_ab erzeugten Untergruppe in (Z/p^e)^x
  C) p=2-Separation: D_eff_odd vs D_raw

Kernfrage: Deckt C_LL^max den Defekt D_eff fuer alle extremalen Tripel?
"""
import math
from itertools import product as iterproduct

def factorize(n):
    factors = {}
    d = 2
    while d * d <= abs(n):
        while n % d == 0:
            factors[d] = factors.get(d, 0) + 1
            n //= d
        d += 1
    if abs(n) > 1:
        factors[abs(n)] = factors.get(abs(n), 0) + 1
    return factors

def rad(n):
    return math.prod(factorize(n).keys()) if n > 1 else 1

def euler_phi(n):
    result = n
    for p in factorize(n).keys():
        result = result * (p - 1) // p
    return result

def multiplicative_order(a, n):
    """Order of a in (Z/nZ)^x. Returns 0 if gcd(a,n) != 1."""
    if math.gcd(a, n) != 1:
        return 0
    order = 1
    current = a % n
    phi = euler_phi(n)
    while current != 1:
        current = (current * a) % n
        order += 1
        if order > phi:
            return 0
    return order

def subgroup_order(generators, modulus):
    """Order of subgroup generated by generators in (Z/modulus)^x.
    For small moduli, enumerate. For large, use order-based estimate."""
    if modulus <= 1:
        return 1
    gens = [g % modulus for g in generators if math.gcd(g, modulus) == 1]
    if not gens:
        return 1

    if modulus < 100000:
        # Enumerate subgroup directly
        subgroup = {1}
        frontier = set(gens)
        while frontier - subgroup:
            subgroup |= frontier
            new_frontier = set()
            for g in gens:
                for s in list(subgroup):
                    new_frontier.add((s * g) % modulus)
                    inv = pow(g, -1, modulus) if math.gcd(g, modulus) == 1 else 0
                    if inv:
                        new_frontier.add((s * inv) % modulus)
            frontier = new_frontier - subgroup
            if len(subgroup) > 50000:
                break
        return len(subgroup)
    else:
        # For large moduli: product of individual orders (upper bound)
        # More accurate: LCM of orders
        orders = [multiplicative_order(g, modulus) for g in gens]
        orders = [o for o in orders if o > 0]
        if not orders:
            return 1
        lcm = orders[0]
        for o in orders[1:]:
            lcm = lcm * o // math.gcd(lcm, o)
        return lcm


triplets = [
    (1, 8, 9), (3, 125, 128), (1, 80, 81), (32, 49, 81),
    (5, 27, 32), (13, 243, 256), (1, 4374, 4375),
    (2, 6436341, 6436343),  # Reyssat
    (1, 2, 3), (1, 63, 64), (7, 18, 25), (1, 242, 243),
    (3, 253, 256), (1, 2400, 2401), (1, 4913, 4914),
    (2, 6561, 6563), (1, 12167, 12168), (1, 512, 513),
    (1, 48, 49), (5, 1024, 1029),
]

# Validate
clean = [(a,b,c) for a,b,c in triplets if a+b==c and math.gcd(a,b)==1]
clean.sort(key=lambda t: math.log(t[2])/math.log(rad(t[0]*t[1]*t[2])), reverse=True)

print("=" * 130)
print("EXTENDED CENSUS: Level-Lowering + S-Unit Congruence + p=2 Separation")
print("=" * 130)
print()

# ===== PART A: Level-Lowering Capacity =====
print("## TEIL A: Level-Lowering Capacity")
print()
print(f"{'Tripel':<28} {'q':>5} {'D_eff':>7} {'C_LL_max':>8} {'ell*':>4} {'Primes_dropped':>20} {'Deckung':>10}")
print("-" * 95)

ll_results = []
for a, b, c in clean:
    fa, fb, fc = factorize(a), factorize(b), factorize(c)
    N = rad(a * b * c)
    logN = math.log(N)
    q_val = math.log(c) / logN

    # D_eff (odd only for now)
    all_primes = set(list(fa.keys()) + list(fb.keys()) + list(fc.keys()))
    log_u = 0
    for p in all_primes:
        if p == 2: continue
        vp = fa.get(p,0) + fb.get(p,0) + fc.get(p,0)
        u_p = (2*vp) // 12
        if u_p > 0:
            log_u += u_p * math.log(p)
    D_eff = math.log(c) - logN - 2*log_u

    # v_p(Delta) for Frey curve: Delta = 16(abc)^2
    # v_p(Delta) = 2*v_p(abc) for p odd, v_2(Delta) = 4 + 2*v_2(abc)
    v_delta = {}
    for p in all_primes:
        vp_abc = fa.get(p,0) + fb.get(p,0) + fc.get(p,0)
        if p == 2:
            v_delta[p] = 4 + 2*vp_abc
        else:
            v_delta[p] = 2*vp_abc

    # For each ell >= 2, compute C_LL(ell) = log(prod{p|N : ell|v_p(Delta)})
    best_ell = 0
    best_c_ll = 0
    best_primes = []

    for ell in range(2, 30):
        dropped = [p for p in all_primes if p in v_delta and v_delta[p] >= ell and v_delta[p] % ell == 0]
        if dropped:
            c_ll = sum(math.log(p) for p in dropped)
            if c_ll > best_c_ll:
                best_c_ll = c_ll
                best_ell = ell
                best_primes = sorted(dropped)

    coverage = "JA" if best_c_ll > max(0, D_eff) else "NEIN"
    gap = best_c_ll - D_eff

    label = f"({a},{b},{c})"
    primes_str = str(best_primes) if best_primes else "-"
    print(f"{label:<28} {q_val:>5.3f} {D_eff:>7.3f} {best_c_ll:>8.3f} {best_ell:>4} {primes_str:>20} {coverage:>6} ({gap:+.3f})")

    ll_results.append({
        'a': a, 'b': b, 'c': c, 'q': q_val, 'D_eff': D_eff,
        'C_LL_max': best_c_ll, 'ell_star': best_ell,
        'primes_dropped': best_primes, 'gap': gap
    })

print()
covered = sum(1 for r in ll_results if r['gap'] > 0 and r['D_eff'] > 0)
total_pos = sum(1 for r in ll_results if r['D_eff'] > 0)
print(f"Level-Lowering deckt {covered}/{total_pos} Tripel mit D_eff > 0")
print()

# ===== PART B: S-Unit Congruence Capacity =====
print("=" * 130)
print("## TEIL B: S-Unit Congruence Capacity")
print()
print("Fuer jedes p^e | c (p > 2): Berechne Ordnung der von S_ab erzeugten")
print("Untergruppe in (Z/p^e)^x. Vergleiche log|<S_ab>| mit e*log(p).")
print()
print(f"{'Tripel':<28} {'p^e|c':>8} {'e*logp':>7} {'|<S_ab>|':>10} {'log|G|':>7} {'log|G|/e*logp':>14}")
print("-" * 90)

for a, b, c in clean:
    fa, fb, fc = factorize(a), factorize(b), factorize(c)
    N = rad(a * b * c)
    q_val = math.log(c) / math.log(N)

    # Only look at p^e | c with e >= 2, p > 2
    c_powers = [(p, e) for p, e in fc.items() if p > 2 and e >= 2]
    if not c_powers:
        continue

    # S_ab = prime support of a*b (excluding p)
    S_ab = set(list(fa.keys()) + list(fb.keys()))

    label = f"({a},{b},{c})"
    for p, e in sorted(c_powers):
        modulus = p ** e
        # Generators: all primes in S_ab that are coprime to p^e
        gens = [q for q in S_ab if q != p and math.gcd(q, modulus) == 1]

        if not gens:
            print(f"{label:<28} {p}^{e}={modulus:>6} {e*math.log(p):>7.3f} {'(no gens)':>10} {'-':>7} {'-':>14}")
            continue

        # Compute subgroup order
        grp_order = subgroup_order(gens, modulus)
        log_grp = math.log(grp_order) if grp_order > 0 else 0
        target = e * math.log(p)
        ratio = log_grp / target if target > 0 else 0

        # Check: is -a/b ≡ 1 (mod p^e) actually satisfied?
        # Since a+b=c and p^e|c, we have a+b ≡ 0 (mod p^e), so -a/b ≡ 1 (mod p^e)
        # This means -a*b^{-1} mod p^e should be 1... wait:
        # a + b = c, p^e|c => a ≡ -b (mod p^e) => a/b ≡ -1 (mod p^e)
        # So -a/b ≡ 1 (mod p^e). Verified.

        print(f"{label:<28} {p}^{e}={modulus:>6} {target:>7.3f} {grp_order:>10} {log_grp:>7.3f} {ratio:>14.4f}")
        label = " " * 28  # indent continuation lines

print()
print("Interpretation: ratio = log|<S_ab>|/(e*log p)")
print("  ratio >> 1: Untergruppe ist GROSS -> tiefe Landung ist 'billig' (viele Moeglichkeiten)")
print("  ratio << 1: Untergruppe ist KLEIN -> tiefe Landung ist 'teuer' (wenige Moeglichkeiten)")
print("  Fuer abc-Beweis brauchen wir: ratio KLEIN bei extremalen Tripeln (Widerspruch)")
print()

# ===== PART C: p=2 Separation =====
print("=" * 130)
print("## TEIL C: p=2 Separation")
print()
print(f"{'Tripel':<28} {'q':>5} {'D_raw':>7} {'D_eff':>7} {'D_eff_odd':>9} {'v2(abc)':>7} {'2-Anteil':>8}")
print("-" * 85)

for a, b, c in clean:
    fa, fb, fc = factorize(a), factorize(b), factorize(c)
    N = rad(a * b * c)
    logN = math.log(N)
    q_val = math.log(c) / logN
    D_raw = math.log(c) - logN

    # D_eff with ALL primes (including p=2 Neron correction)
    all_primes = set(list(fa.keys()) + list(fb.keys()) + list(fc.keys()))
    log_u_all = 0
    log_u_odd = 0
    for p in all_primes:
        vp = fa.get(p,0) + fb.get(p,0) + fc.get(p,0)
        u_p = (2*vp) // 12
        if u_p > 0:
            if p != 2:
                log_u_odd += u_p * math.log(p)
            log_u_all += u_p * math.log(p)

    D_eff_full = math.log(c) - logN - 2*log_u_all
    D_eff_odd = math.log(c) - logN - 2*log_u_odd

    v2_abc = fa.get(2,0) + fb.get(2,0) + fc.get(2,0)
    two_contrib = 2*log_u_all - 2*log_u_odd  # how much p=2 Neron removes

    label = f"({a},{b},{c})"
    print(f"{label:<28} {q_val:>5.3f} {D_raw:>7.3f} {D_eff_full:>7.3f} {D_eff_odd:>9.3f} {v2_abc:>7} {two_contrib:>8.3f}")

print()
print("Interpretation:")
print("  D_raw = log(c) - log(N)  [roher Defekt ohne Neron]")
print("  D_eff = D_raw - 2*log(u_all)  [mit allen Neron-Korrekturen]")
print("  D_eff_odd = D_raw - 2*log(u_odd)  [nur odd-Neron; p=2 unkorrigiert]")
print("  2-Anteil = Differenz D_eff_odd - D_eff  [was p=2-Neron entfernt]")
print("  Falls 2-Anteil gross: Hauptdefekt ist 2-adisch, nicht odd-Tamagawa")
print()

# ===== SUMMARY =====
print("=" * 130)
print("## ZUSAMMENFASSUNG: Welche Capacity deckt welche Tripel?")
print("=" * 130)
print()
print(f"{'Tripel':<28} {'D_eff':>7} {'C_LL':>7} {'LL deckt':>9} {'S-Unit deckt':>12}")
print("-" * 75)

for r in ll_results:
    if r['D_eff'] <= 0:
        continue
    a, b, c = r['a'], r['b'], r['c']
    fa, fb, fc = factorize(a), factorize(b), factorize(c)

    # S-Unit check: for the LARGEST p^e|c, is subgroup small or large?
    c_powers = [(p, e) for p, e in fc.items() if p > 2 and e >= 2]
    S_ab = set(list(fa.keys()) + list(fb.keys()))
    su_verdict = "-"
    if c_powers:
        p_max, e_max = max(c_powers, key=lambda x: x[1]*math.log(x[0]))
        modulus = p_max ** e_max
        gens = [q for q in S_ab if q != p_max and math.gcd(q, modulus) == 1]
        if gens:
            grp_order = subgroup_order(gens, modulus)
            phi_m = euler_phi(modulus)
            # "covers" if subgroup is small relative to phi
            ratio = grp_order / phi_m
            su_verdict = f"ratio={ratio:.4f}"

    ll_covers = "JA" if r['gap'] > 0 else f"NEIN({r['gap']:+.2f})"
    label = f"({a},{b},{c})"
    print(f"{label:<28} {r['D_eff']:>7.3f} {r['C_LL_max']:>7.3f} {ll_covers:>9} {su_verdict:>12}")

print()
print("KERNFRAGE: Deckt Level-Lowering-Capacity ALLE D_eff>0 Tripel?")
all_covered = all(r['gap'] > 0 for r in ll_results if r['D_eff'] > 0)
print(f"  Antwort: {'JA — alle gedeckt!' if all_covered else 'NEIN — Luecken vorhanden.'}")
if not all_covered:
    print("  Nicht gedeckte Tripel:")
    for r in ll_results:
        if r['D_eff'] > 0 and r['gap'] <= 0:
            print(f"    ({r['a']},{r['b']},{r['c']}): D_eff={r['D_eff']:.3f}, C_LL={r['C_LL_max']:.3f}, gap={r['gap']:+.3f}")
