"""Requirements ledger for true Hecke-maximal-ideal projections.

EM-3a only reduced normalized modular-symbol values modulo active drop primes.
That is not a projection to a Hecke maximal ideal.  This script lists the active
drop pairs and estimates what a real test of pi_m(C_lambda) would require:

  - modular-symbol / homology module at level N over F_l,
  - Hecke maximal ideal m_l generated by l and eigenvalue congruences,
  - localization or quotient at m_l,
  - image of the Frey Farey cycle C_lambda in that quotient.

The dimension and Sturm estimates are deliberately coarse; they are feasibility
flags, not theorem statements.
"""

from __future__ import annotations

import json
import math
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "_data" / "em4_c3_capacity_obstruction_2026-05-09.json"
OUTPUT = ROOT / "_data" / "g1_maxideal_projection_requirements_2026-05-09.json"


def prime_factors(n: int) -> list[int]:
    factors: list[int] = []
    d = 2
    while d * d <= n:
        if n % d == 0:
            factors.append(d)
            while n % d == 0:
                n //= d
        d += 1 if d == 2 else 2
    if n > 1:
        factors.append(n)
    return factors


def gamma0_index(n: int) -> float:
    value = float(n)
    for p in prime_factors(n):
        value *= 1.0 + 1.0 / p
    return value


def dim_heuristic(n: int) -> float:
    return gamma0_index(n) / 12.0


def sturm_bound_weight2(n: int) -> int:
    return max(1, math.floor(gamma0_index(n) / 6.0))


def product(values: list[int]) -> int:
    result = 1
    for value in values:
        result *= int(value)
    return result


def feasibility(dim: float, sturm: int) -> str:
    if dim <= 1000 and sturm <= 5000:
        return "small"
    if dim <= 10000 and sturm <= 50000:
        return "medium"
    return "hard"


def row_for_pair(entry: dict, ell_text: str, drop_primes: list[int]) -> dict:
    ell = int(ell_text)
    n = int(entry["N_cond"])
    d_ell = product(drop_primes)
    residual_level = n // d_ell if d_ell else n
    dim_n = dim_heuristic(n)
    dim_residual = dim_heuristic(residual_level)
    sturm_n = sturm_bound_weight2(n)
    return {
        "label": entry["label"],
        "a": entry["a"],
        "b": entry["b"],
        "c": entry["c"],
        "quality": entry["quality"],
        "ell": ell,
        "N_cond": n,
        "D_ell": d_ell,
        "drop_primes": drop_primes,
        "residual_level_heuristic": residual_level,
        "dim_level_heuristic": dim_n,
        "dim_residual_level_heuristic": dim_residual,
        "sturm_bound_level_weight2": sturm_n,
        "dimension_ratio_residual_to_full": dim_residual / dim_n if dim_n else 0.0,
        "feasibility": feasibility(dim_n, sturm_n),
        "true_test_requires": [
            "construct modular symbols/homology at level N over F_ell",
            "construct Hecke operators T_q up to enough separating precision",
            "form maximal ideal m=(ell, T_q-a_q(E), local U_p/Atkin-Lehner constraints)",
            "localize or quotient the homology module at m",
            "map the Frey Farey cycle C_lambda to the localized quotient",
            "compare with matched random cycles in the same quotient",
        ],
    }


def main() -> None:
    source = json.loads(INPUT.read_text(encoding="utf-8"))
    rows: list[dict] = []
    for entry in source:
        for ell_text, drop_primes in entry["drop_by_ell"].items():
            if drop_primes:
                rows.append(row_for_pair(entry, ell_text, drop_primes))

    rows.sort(key=lambda r: ({"small": 0, "medium": 1, "hard": 2}[r["feasibility"]], r["N_cond"], r["ell"]))
    counts: dict[str, int] = {"small": 0, "medium": 0, "hard": 0}
    for row in rows:
        counts[row["feasibility"]] += 1

    result = {
        "date": "2026-05-09",
        "purpose": "Identify what a true G1/P1' Hecke-maximal-ideal projection test would require.",
        "distinction_from_em3a": (
            "EM-3a reduced modular-symbol values modulo ell; a true test must "
            "localize/quotient the modular-symbol module at the Hecke maximal "
            "ideal m_ell before evaluating C_lambda."
        ),
        "summary": {
            "active_pairs": len(rows),
            "feasibility_counts": counts,
            "small_first_candidates": [
                {
                    "label": row["label"],
                    "ell": row["ell"],
                    "N_cond": row["N_cond"],
                    "D_ell": row["D_ell"],
                    "dim": row["dim_level_heuristic"],
                    "sturm": row["sturm_bound_level_weight2"],
                }
                for row in rows
                if row["feasibility"] == "small"
            ][:8],
            "conclusion": (
                "The next executable G1/P1' step is not another residue scan, "
                "but a Sage/Magma-style Hecke localization for the small active "
                "pairs, followed by matched controls in the same localized quotient."
            ),
        },
        "active_pairs": rows,
    }
    OUTPUT.write_text(json.dumps(result, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
