"""Emit a PARI/GP modular-symbol scan for high-quality Frey triples.

The emitted GP code uses msfromell(E) and evaluates the period-normalized
symbols x^+, x^- along the canonical continued-fraction/Farey path from
0 to lambda=a/(a+b).
"""

from __future__ import annotations

from dataclasses import dataclass
from fractions import Fraction
import argparse
from pathlib import Path


@dataclass(frozen=True)
class Triple:
    a: int
    b: int
    label: str
    q: float

    @property
    def c(self) -> int:
        return self.a + self.b


TRIPLES = [
    Triple(1, 4374, "1+4374=4375", 1.568),
    Triple(1, 2400, "1+2400=2401", 1.456),
    Triple(3, 125, "3+125=128", 1.427),
    Triple(625, 2048, "625+2048=2673", 1.361),
    Triple(289, 6272, "289+6272=6561", 1.338),
    Triple(1, 5831, "1+5831=5832", 1.320),
    Triple(1, 512, "1+512=513", 1.318),
    Triple(1, 242, "1+242=243", 1.311),
    Triple(5, 1024, "5+1024=1029", 1.297),
    Triple(1, 80, "1+80=81", 1.292),
    Triple(10, 2187, "10+2187=2197", 1.290),
    Triple(13, 243, "13+243=256", 1.273),
    Triple(125, 2187, "125+2187=2312", 1.242),
    Triple(81, 1250, "81+1250=1331", 1.240),
    Triple(1, 6560, "1+6560=6561", 1.235),
    Triple(1, 6859, "1+6859=6860", 1.228),
    Triple(1, 8, "1+8=9", 1.226),
    Triple(1, 288, "1+288=289", 1.225),
    Triple(1, 6655, "1+6655=6656", 1.212),
    Triple(11, 3125, "11+3125=3136", 1.211),
    Triple(49, 576, "49+576=625", 1.204),
    Triple(243, 1805, "243+1805=2048", 1.202),
]


def continued_fraction(frac: Fraction) -> list[int]:
    n, d = frac.numerator, frac.denominator
    out: list[int] = []
    while d:
        q, n = divmod(n, d)
        out.append(q)
        n, d = d, n
    return out


def convergents(cf: list[int]) -> list[Fraction]:
    conv: list[Fraction] = []
    p0, p1 = 0, 1
    q0, q1 = 1, 0
    for a in cf:
        p0, p1 = p1, a * p1 + p0
        q0, q1 = q1, a * q1 + q0
        conv.append(Fraction(p1, q1))
    return conv


def farey_edges(frac: Fraction) -> list[tuple[Fraction, Fraction]]:
    conv = convergents(continued_fraction(frac))
    if conv[0] != 0:
        conv.insert(0, Fraction(0, 1))
    return list(zip(conv, conv[1:]))


def gp_fraction(x: Fraction) -> str:
    if x.denominator == 1:
        return str(x.numerator)
    return f"{x.numerator}/{x.denominator}"


def gp_paths(a: int, c: int) -> str:
    edges = farey_edges(Fraction(a, c))
    return "[" + ", ".join(f"[{gp_fraction(u)}, {gp_fraction(v)}]" for u, v in edges) + "]"


def emit_gp(triples: list[Triple]) -> str:
    header = r"""\\ Frey modular-symbol scan generated by make_pari_symbol_scan.py
\\p 50

absreal(x) = abs(x + 0.0);
frey_curve(a, b) = ellinit([0, b-a, 0, -a*b, 0]);

report_symbol_frame(label, qabc, a, b, paths) =
{
  my(c = a + b);
  my(E = frey_curve(a, b));
  my(N = ellglobalred(E)[1]);
  my(w = ellrootno(E));
  my(ms = msfromell(E, 0));
  my(M = ms[1]);
  my(x = ms[2]);
  my(xp = x[1]);
  my(xm = x[2]);
  my(windp = mseval(M, xp, [0, oo]));
  my(windm = mseval(M, xm, [0, oo]));
  my(maxp = 0.0, maxm = 0.0, maxboth = 0.0);

  for(i = 1, #paths,
    my(vp = mseval(M, xp, paths[i]));
    my(vm = mseval(M, xm, paths[i]));
    my(ap = absreal(vp));
    my(am = absreal(vm));
    my(ab = max(ap, am));
    if(ap > maxp, maxp = ap);
    if(am > maxm, maxm = am);
    if(ab > maxboth, maxboth = ab);
  );

  printf("SUMMARY | %s | q=%.3f | a=%d | b=%d | c=%d | Ncond=%d | rootno=%d | dim=%d | edges=%d | winding_plus=%Ps | winding_minus=%Ps | max_xplus=%.12g | max_xminus=%.12g | max_frame=%.12g\n",
         label, qabc, a, b, c, N, w, msdim(M), #paths, windp, windm, maxp, maxm, maxboth);
};

"""
    calls = []
    for t in triples:
        calls.append(
            f'report_symbol_frame("{t.label}", {t.q:.3f}, {t.a}, {t.b}, {gp_paths(t.a, t.c)});'
        )
    return header + "\n".join(calls) + "\n\nquit;\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--limit", type=int, default=len(TRIPLES))
    parser.add_argument("--out", type=Path)
    args = parser.parse_args()

    code = emit_gp(TRIPLES[: args.limit])
    if args.out:
        args.out.write_text(code, encoding="utf-8")
    else:
        print(code)


if __name__ == "__main__":
    main()
