"""Emit a PARI/GP scan for local Farey-star modular-symbol frames.

For lambda=a/c, the previous P1 scan used the continued-fraction path from
0 to lambda. This generator instead uses all Farey edges incident to lambda
with denominator bounded by H. It is designed to test whether null cases on
the single path disappear in the local cell.
"""

from __future__ import annotations

from dataclasses import dataclass
from fractions import Fraction
import argparse
from pathlib import Path


@dataclass(frozen=True)
class Triple:
    a: int
    b: int
    label: str
    q: float

    @property
    def c(self) -> int:
        return self.a + self.b


TRIPLES = [
    Triple(1, 6560, "1+6560=6561", 1.235),
    Triple(1, 4374, "1+4374=4375", 1.568),
    Triple(289, 6272, "289+6272=6561", 1.338),
    Triple(10, 2187, "10+2187=2197", 1.290),
    Triple(625, 2048, "625+2048=2673", 1.361),
]


def farey_star_edges(a: int, c: int, h: int) -> list[tuple[Fraction, Fraction]]:
    lam = Fraction(a, c)
    neighbors: set[Fraction] = set()
    for s in range(1, h + 1):
        for sign in (-1, 1):
            num = c * 0  # marker for readability below
            candidate = a * s + sign
            if candidate % c:
                continue
            r = candidate // c
            if 0 <= r <= s:
                neighbors.add(Fraction(r, s))
    neighbors.discard(lam)
    return [(lam, nb) for nb in sorted(neighbors)]


def gp_fraction(x: Fraction) -> str:
    if x.denominator == 1:
        return str(x.numerator)
    return f"{x.numerator}/{x.denominator}"


def gp_paths(paths: list[tuple[Fraction, Fraction]]) -> str:
    return "[" + ", ".join(f"[{gp_fraction(u)}, {gp_fraction(v)}]" for u, v in paths) + "]"


def emit_gp(triples: list[Triple], h_factor: float, h_extra: int) -> str:
    header = r"""\\ Local Farey-star modular-symbol scan generated by make_pari_local_star_scan.py
\\p 50

absreal(x) = abs(x + 0.0);
frey_curve(a, b) = ellinit([0, b-a, 0, -a*b, 0]);

report_symbol_frame(label, qabc, a, b, hbound, paths) =
{
  my(c = a + b);
  my(E = frey_curve(a, b));
  my(N = ellglobalred(E)[1]);
  my(w = ellrootno(E));
  my(ms = msfromell(E, 0));
  my(M = ms[1]);
  my(x = ms[2]);
  my(xp = x[1]);
  my(xm = x[2]);
  my(maxp = 0.0, maxm = 0.0, maxboth = 0.0);
  my(top = 0, top_p = 0, top_m = 0);

  for(i = 1, #paths,
    my(vp = mseval(M, xp, paths[i]));
    my(vm = mseval(M, xm, paths[i]));
    my(ap = absreal(vp));
    my(am = absreal(vm));
    my(ab = max(ap, am));
    if(ap > maxp, maxp = ap);
    if(am > maxm, maxm = am);
    if(ab > maxboth,
      maxboth = ab;
      top = i;
      top_p = vp;
      top_m = vm;
    );
  );

  printf("SUMMARY | %s | q=%.3f | a=%d | b=%d | c=%d | H=%d | Ncond=%d | rootno=%d | dim=%d | star_edges=%d | max_xplus=%.12g | max_xminus=%.12g | max_frame=%.12g | top_edge=%d | top_xplus=%Ps | top_xminus=%Ps\n",
         label, qabc, a, b, c, hbound, N, w, msdim(M), #paths, maxp, maxm, maxboth, top, top_p, top_m);
};

"""
    calls = []
    for t in triples:
        h = int(t.c * h_factor) + h_extra
        paths = farey_star_edges(t.a, t.c, h)
        calls.append(
            f'report_symbol_frame("{t.label}", {t.q:.3f}, {t.a}, {t.b}, {h}, {gp_paths(paths)});'
        )
    return header + "\n".join(calls) + "\n\nquit;\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--limit", type=int, default=len(TRIPLES))
    parser.add_argument("--h-factor", type=float, default=1.0)
    parser.add_argument("--h-extra", type=int, default=1)
    parser.add_argument("--out", type=Path)
    args = parser.parse_args()

    code = emit_gp(TRIPLES[: args.limit], args.h_factor, args.h_extra)
    if args.out:
        args.out.write_text(code, encoding="utf-8")
    else:
        print(code)


if __name__ == "__main__":
    main()
